[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dataroute"
version = "0.1.0"
description = "Описание вашей библиотеки"
readme = "README.md"
authors = [
    {name = "Ваше Имя", email = "your.email@example.com"},
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.28.0",
]
requires-python = ">=3.8"

[project.urls]
"Homepage" = "https://github.com/username/dataroute"
"Bug Tracker" = "https://github.com/username/dataroute/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/dataroute"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black" 